### PR TITLE
Improve RTF for 3D Livox Lidar 

### PR DESCRIPTION
**Pull request by arturocuma**
Comment traceHandle on ASYNC for now, not sure if this should be removed

### CODE REVIEW

**Review by yuokamoto — COMMENTED** [review]
you should not just comment out but override in child class

**Comment by arturocuma** [comment]
> you should not just comment out but override in child class

@yuokamoto it is already overwritten but it calls Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
Should I inherit directly RRLiVoxMid360Component from URRBaseLidarComponent?

**Comment by yuokamoto** [comment]
> > you should not just comment out but override in child class
> 
> @yuokamoto it is already overwritten but it calls Super::TickComponent(DeltaTime, TickType, ThisTickFunction); Should I inherit directly RRLiVoxMid360Component from URRBaseLidarComponent?

1. if most of the logic is not same, you can inherit from URRBaseLidarComponent
2. you can change it not call super Tick or call URRBaseLidarComponent::TickComponent instead of Super::TickComponent

**Comment by arturocuma** [comment]
> > > you should not just comment out but override in child class
> > 
> > 
> > @yuokamoto it is already overwritten but it calls Super::TickComponent(DeltaTime, TickType, ThisTickFunction); Should I inherit directly RRLiVoxMid360Component from URRBaseLidarComponent?
> 
> 1. if most of the logic is not same, you can inherit from URRBaseLidarComponent
> 2. you can change it not call super Tick or call URRBaseLidarComponent::TickComponent instead of Super::TickComponent

Thanks, I will go with call URRBaseLidarComponent::TickComponent instead of Super::TickComponent

**Comment by arturocuma** [comment]
We can close this PR as the changes can be done on RapyutaSimulationInternal

**Pull request closed without merging**
